all_tests_debian_unstable:
    image: debian:sid
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-dask python3-pint python3-requests python3-statsmodels python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel
    - apt-get install -qy python3-sympy --no-install-recommends
    - apt-get install -qy python3-pytest python3-pytest-cov xvfb
    - pip3 install --upgrade pip
    - pip3 install --user .
    - xvfb-run -a python3 -m pytest --doctest-modules --cov=fpd_data_processing fpd_data_processing/
    - xvfb-run -a python3 -m pytest --doctest-glob="*.rst" doc/

flake8_checks:
    image: debian:sid
    script:
    - apt-get update -q
    - apt-get install -qy python3-flake8
    - python3 -m flake8 --exclude fpd_data_processing/api.py fpd_data_processing/

pydocstyle_checks:
    image: debian:sid
    script:
    - apt-get update -q
    - apt-get install -qy python3-pydocstyle
    - python3 -m pydocstyle fpd_data_processing/
    allow_failure: true

make_documentation:
    image: debian:unstable
    stage: deploy
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-dask python3-pint python3-requests python3-statsmodels python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel
    - apt-get install -qy python3-sympy --no-install-recommends
    - apt-get install -qy xvfb python3-sphinx python3-sphinx-rtd-theme build-essential
    - pip3 install .
    - cd doc
    - cd images/analysing_holz_datasets/
    - xvfb-run -a python3 testdata.py
    - cd ../analysing_holz_datasets/
    - xvfb-run -a python3 make_dpc_analysis_images.py
    - cd ../frontpage/
    - xvfb-run -a python3 make_frontpage_images.py
    - cd ../../
    - make html
    - cd ..
    - mv doc/_build/html documentation
    artifacts:
        paths:
        - documentation
